name: Build Android and iOS
on: [push, pull_request]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
      needs: install-and-test
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - name: Install npm dependencies
          run: |
            npm install
        - name: Build Android Release
          run: |
            cd android && ./gradlew assembleRelease
  build-ios:
    needs: install-and-test
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |       
          xcodebuild -workspace Simian.xcworkspace -scheme Simian archive -archivePath Simian.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./Simian.xcarchive -exportPath . -exportOptionsPlist Simian/Info.plist
          mv Simian.ipa ../Simian.ipa