name: Build Android and iOS
on: [push, pull_request]
jobs:
  build-android:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout repo
          uses: actions/checkout@v2
              
        - name: Install npm dependencies
          run: |
            npm install

        - name: Build Android
          run: |
            cd android && ./gradlew assembleDebug

  build-ios:
    runs-on: macos-latest
    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v2
            
      - name: Install npm dependencies
        run: |
          npm install

      - name: Cache CocoaPods dependencies
        uses: actions/cache@v2
        id: cache-pods
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods

      - name: Install pod dependencies
        run: |
          cd ios && pod install

      - name: Build iOS
        run: |       
          xcodebuild \
          -workspace ios/Simian.xcworkspace \
          -scheme Simian \
          CODE_SIGNING_ALLOWED=NO